version: '3.1'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - '5009:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TodoDb

  todos_api:
    image: todosapi
    container_name: todos_api
    build:
      context: .
      dockerfile: src/Todos.Api/Dockerfile
    restart: always
    ports:
      - '5005:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    #links:
    #  - 'postgres_db'

  auth_api:
    image: authapi
    container_name: auth_api
    build:
      context: .
      dockerfile: auth/Todos.AuthApi/Dockerfile
    restart: always
    ports:
      - '5007:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    links:
      - 'todos_api'

  todos_ui:
    image: todosui
    container_name: todos_ui
    build:
      context: .
      dockerfile: src/Todos.Spa/AngularUI/Dockerfile
    restart: always
    ports:
      - '5009:80'
    links:
      - 'auth_api'