version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    - '5005:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest

  todosapi:
    image: todosapi
    container_name: todosapi
    build: .
    restart: always
    ports:
    - '5001:80'
    links:
    - 'mongo'

  authapi:
    image: authapi
    container_name: authapi
    build: .
    restart: always
    ports:
    - '5003:80'
    links:
    - 'todosapi'