version: '3.1'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - '5009:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TodoDb